### ISSUE TITLE
Slow loading 

### ISSUE THREAD

**Issue by pakom** [jmcvw/mrup#5]
Thank you for the nice plugin, this is something I was looking for, but got aware about recently.

I installed your plugin and tried to use it. However, none of the buttons respond, the button icons are missing and the window is blank, no previously used projects are displayed. I am not able to do anything. Although the guide in the README says "It may take several seconds to complete the search, with the time increasing the closer you get to the root directory of a hard disk.", in my case it takes about three minutes. I don't think this is due to a slow computer because I have quite powerful machine with 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (eight cores) and 64BG of RAM.

About a minute after I start the plugin, I get the following printed in the console nearly 400 times:

`Warning in list.dirs(search_dir, full.names = TRUE, recursive = FALSE) :`
`   over-long path`

About two minutes after this I get the plugin working.

**Comment by jmcvw** [comment]
Hey @pakom, many thanks for telling me of this. This is the main reason I haven't tried to share this more widely - I'm not really much of a programmer! You might just be the only other person in the world to have installed this 😆 

However, I believe it was a very simple issue ,which affected only Windows machines (??). Mine already had the fix applied locally., so I missed it.

I have pushed the fix so hopefully it works now.

Please re-install, and try again.

**Comment by pakom** [comment]
Huh, not much of a programmer myself, just trying to be :grinning:

In Windows I reinstalled it and tried it again. I still get the same warning as before and the performance is the same. Related to the [other issue](https://github.com/thomasp85/shinyFiles/issues/167#issue-1224679553), still no volume in the drop-down menu, when change the volume it does not update the tree, and then when clicking on a folder the plugin crashes.

I also tried in Linux. There it never fully loaded, waited for about half an hour. I suppose this is because the Linux file system is endless and quite more complex than in Windows, so it takes very long time to ransack the entre file system.

**Comment by jmcvw** [comment]
Hmmm, how strange.

My addin works fine for me on both Mac and Windows (mostly see below).
My Windows machine with two internal HDDs (200 and 500 GB), loads in 5-6 seconds.
I will see if I can try a few other machines next week.
The last time it was tested on Linux was maybe maybe 2 years ago, so all bets are off with Linux.

Interestingly however, I just discovered that while my addin works fine for my general use, if I select the root dir (i.e. `C:` or `D:`) then it fails with the same warning you mentioned in the shinyFiles issue.

```
Warning: Error in if: argument is of length zero
  51: traverseDirs
  50: <Anonymous>
  48: sendDirectoryData
  47: observe
  46: <observer>
   3: shiny::runApp
   2: runGadget
   1: mrup:::mrup
```

**Comment by pakom** [comment]
> Interestingly however, I just discovered that while my addin works fine for my general use, if I select the root dir (i.e. `C:` or `D:`) then it fails with the same warning you mentioned in the shinyFiles issue.

Yes, upon loading it does load `C:` in the tree and leaves the drop-down menu for volume selection. Then it works fine. But if you choose a volume, even if it is `C:` then the issue appears. But this is an issue of the `shinyFiles` package, not of your plugin.

> My Windows machine with two internal HDDs (200 and 500 GB), loads in 5-6 seconds.

OK, so these are two separate physical drives, so each one of them has one volume only. In my case it is a single drive with more than one **logical** volumes which, I believe, would make the difference.

**Comment by jmcvw** [comment]
Hey @pakom. My addin seems to be working as it should now. If it looks useful to you, it would be great to hear if it works.
Thanks for your input.

**Comment by pakom** [comment]
I can confirm I am able to change the volumes successfully after the last changes in `shinyFiles`.

However, the issues with the slow loading and the warning still persist.

As for the slow loading, correct me if I'm wrong, I think this is because you initially list all folders with the `dirRecur` function in your `helpers.R` (`dirs <- list.dirs(search_dir, full.names = TRUE, recursive = FALSE)`). I don't know your machine, but on mine I have quite a lot of stuff, so I guess the slow loading issue is that it takes too long to list all possible folders. But is listing absolutely everything really needed? Maybe just showing the volumes, so the user can navigate would be more simple and avoid the issue? I presume this could also save the trouble with the warning for the overly long paths. For example, some directories in `C:\Windows` can go quite deep, and even deeper in Linux system volumes.

Further, after choosing a project folder, I see the following:
![Screen-2022-05-08_15-26-56](https://user-images.githubusercontent.com/15523823/167298410-9927ccb0-8229-4292-a1ec-e746abae7344.png)
I am not sure what `(days)` stand for. Regardless if I click on it or not (i.e. leaving empty the drop-down list), clicking on the "Open" button below the "Projects" drop-down list crashes the addin with the following error:

```
Warning: Error in : 'path' is not a length-one character vector
  3: shiny::runApp
  2: runGadget
  1: mrup:::mrup
```
